# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 9
modify_font cell_height 120%
# END_KITTY_FONTS

placement_strategy top
